### ISSUE TITLE
Why there is an additional channel when N_importance > 0?

### ISSUE THREAD

**Issue by FreemanG** [facebookresearch/nonrigid_nerf#10]
Hi, thanks for you excellent work.

What's the 5th channel uesd for when N_importance > 0? 

https://github.com/facebookresearch/nonrigid_nerf/blob/5187abfe9b9e30e45cb87087f94ff1e00fb4450c/train.py#L593

**Comment by edgar-tr** [comment]
That's just a carry-over from the original source code: https://github.com/yenchenlin/nerf-pytorch/blob/master/run_nerf.py#L187 . My guess is that it's for some experiment to predict some kind of hint for importance sampling. In any case, the fifth channel isn't used anywhere, I just didn't bother to remove it.

**Comment by FreemanG** [comment]
Thanks for your quick reply.
