### ISSUE TITLE
What's the render_poses meaning?

### ISSUE THREAD

**Issue by wtishere** [facebookresearch/nonrigid_nerf#16]
Thanks for your great work! When I ran training.py by using the example_sequence data, I found the loaded data are from precomputed.json, which you provide. I'd like to train other datasets, so could you tell how to compute the precomputed.json? By the way, from precomputed.json, what's the render_poses meaning? And what's the difference between poses and render_poses? Thank you so much!

**Comment by md5xwl** [comment]
I'm having the same problem。In func load_llff_data, poses loaded from data/example_sequence/precomputed.json, not from my dataset.

**Comment by edgar-tr** [comment]
Hi,please follow the optional installation instructions about replacing the included llff files with the original ones: https://github.com/facebookresearch/nonrigid_nerf#installationAfter that, preprocessing estimates the camera parameters:  https://github.com/facebookresearch/nonrigid_nerf#preprocessrender_poses are novel poses for test-time rendering, while poses are the poses for the training images.

**Comment by edgar-tr** [comment]
Hi,    please follow the optional installation instructions about replacing the included llff files with the original ones: https://github.com/facebookresearch/nonrigid_nerf#installation      After that, preprocessing estimates the camera parameters:  https://github.com/facebookresearch/nonrigid_nerf#preprocess       render_poses are novel poses for test-time rendering, while poses are the poses for the training images.

**Comment by wtishere** [comment]
thank you so much.

**Comment by wtishere** [comment]
Thank you so much.
